[project]
name = "fatterbox"
version = "1.0.0"
description = "fatterbox"
requires-python = "==3.11.*"
dependencies = [
    # EXPORT HF_TOKEN="none"
    "tts-webui-chatterbox-tts @ git+https://github.com/rsxdalv/chatterbox.git@faster",
    "wyoming",
    "torch",
    "torchaudio",
    "perth",
]
